In [14]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn import metrics
from sklearn import datasets
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt
from sklearn import cross_val_score
from sklearn.tree import DecisionTreeClassifier
import sklearn
import warnings
warnings.filterwarnings('ignore')

df=datasets.load_iris()

x=df.data
y=df.target
print('class labels :', np.unique(y))

class labels : [0 1 2]


In [15]:
from  sklearn.preprocessing import StandardScaler

ss=StandardScaler()
ss.fit(x)
x=ss.transform(x)

In [18]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y, test_size=0.3,random_state=0)

In [19]:
dtree = tree.DecisionTreeClassifier(criterion= 'entropy', random_state=0)
dtree.fit(X_train,y_train)

print("train  accuracy:", metrics.accuracy_score(y_train, dtree.predict(X_train)))
print("train confusion matrix:", metrics.confusion_matrix(y_train, dtree.predict(X_train)))
print("train classification report :", metrics.classification_report(y_train, dtree.predict(X_train)))
print('\n')
print("test accuracy :", metrics.accuracy_score(y_test, dtree.predict(X_test)))
print("test confusion matrix", metrics.confusion_matrix(y_test, dtree.predict(X_test)))
print("test classification report", metrics.classification_report(y_test, dtree.predict(X_test)))

train  accuracy: 1.0
train confusion matrix: [[34  0  0]
 [ 0 32  0]
 [ 0  0 39]]
train classification report :              precision    recall  f1-score   support

          0       1.00      1.00      1.00        34
          1       1.00      1.00      1.00        32
          2       1.00      1.00      1.00        39

avg / total       1.00      1.00      1.00       105



test accuracy : 0.9777777777777777
test confusion matrix [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
test classification report              precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.94      0.97        18
          2       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        45



In [23]:
import graphviz
ds=tree.export_graphviz(dtree, out_file=None, feature_names=df.feature_names, class_names=df.target_names, filled=True, rounded=True, special_characters=True)
graph =graphviz.Source(ds)
graph.render('df')
ds=tree.export_graphviz(dtree, out_file=None, feature_names=df.feature_names, class_names=df.target_names, filled= True, rounded= True, special_characters= True)
graph=graphviz.Source(ds)
graph

ModuleNotFoundError: No module named 'graphviz'